# .ktlint.yml
android: true
version: 12.1.1
reporter:
  - plain
  - checkstyle
  - html
output:
  color: true
editorconfig:
  /Users/lingzuqi/android-modular-showcase/.editorconfig
experimental:
  rules:
    no-empty-file: true
disabled_rules:
  - import-ordering
  - indent
  - final-newline
  - max-line-length
  - parameter-list-wrapping